#!/usr/bin/env python3
"""Build/check the deterministic publication-state manifest.

The manifest binds the current repository publication state to repository-local
inputs without introducing new research claims.  It records SHA-256 digests for
protocol files, schemas, B2 research objects, registries, build scripts,
dependency contracts, and documented mutable publication-output exclusions.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "releases" / "publication-state-manifest.json"
MANIFEST_SCHEMA_VERSION = "publication-state-manifest-v1"
PROTOCOL_VERSION = "protocol-v1"
INVESTIGATION_ID = "b2-governance-cohort"

REQUIRED_FILES = {
    "ci_workflows": [".github/workflows/validate.yml", ".github/workflows/b2-publication-readiness.yml"],
    "dependency_contracts": ["requirements.txt"],
    "protocol_sources": [
        "protocol/README.md",
        "protocol/changelog.md",
        "protocol/protocol-v1/README.md",
        "protocol/protocol-v1/protocol.md",
        "protocol/protocol-v1/terminology.md",
        "protocol/protocol-v1/decision_rules.md",
    ],
    "registries": [
        "registry/architectural_boundaries.json",
        "registry/candidate_invariants.json",
        "registry/classifications.json",
        "registry/cohort_conclusions.json",
        "registry/investigations.json",
        "registry/protocol_versions.json",
        "registry/retained_classifications.json",
        "registry/terminology.json",
    ],
    "schemas": [
        "schemas/analysis.schema.json",
        "schemas/bor.schema.json",
        "schemas/cohort_conclusion.schema.json",
        "schemas/dataset.schema.json",
        "schemas/der.schema.json",
        "schemas/investigation.schema.json",
        "schemas/msr.schema.json",
        "schemas/retained_classification.schema.json",
        "schemas/srf.schema.json",
    ],
    "builder_scripts": [
        "scripts/build_analysis.py",
        "scripts/build_cohort_conclusion.py",
        "scripts/build_dataset.py",
        "scripts/build_papers.py",
        "scripts/build_publication_manifest.py",
        "scripts/build_retained_classification.py",
        "scripts/check_registry.py",
        "scripts/validate.py",
    ],
    "publication_sources": [
        "README.md",
        "REPRODUCIBILITY.md",
        "docs/publication.md",
        "docs/research_pipeline.md",
    ],
}

RESEARCH_OBJECT_DIRS = {
    "bor_records": ("investigations/b2-governance-cohort/bor", "*.bor.json"),
    "srf_records": ("investigations/b2-governance-cohort/srf", "*.srf.json"),
    "der_records": ("investigations/b2-governance-cohort/der", "*.der.json"),
    "msr_records": ("investigations/b2-governance-cohort/msr", "*.msr.json"),
}

RESEARCH_OBJECT_FILES = {
    "preregistration": ["investigations/b2-governance-cohort/preregistration/i1_i5_registration.json"],
    "comparative_dataset": ["investigations/b2-governance-cohort/dataset/b2-governance-cohort-i4.dataset.json"],
    "analysis": ["investigations/b2-governance-cohort/analysis/b2-governance-cohort-i4.analysis.json"],
    "retained_classification": ["investigations/b2-governance-cohort/results/b2-governance-cohort-i5.retained-classification.json"],
    "cohort_conclusion": ["investigations/b2-governance-cohort/results/b2-governance-cohort-i5.cohort-conclusion.json"],
}

EXCLUDED_MUTABLE_OUTPUTS = [
    {
        "path_glob": "releases/papers/*.pdf",
        "reason": "publication PDFs are generated by scripts/build_papers.py during validation and CI; including them would make manifest checks depend on prior mutable build outputs",
    }
]


def rel(path: Path) -> str:
    return str(path.relative_to(ROOT))


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def require_file(relative: str) -> Path:
    path = ROOT / relative
    if not path.is_file():
        raise SystemExit(f"missing manifest input: {relative}")
    return path


def file_entry(relative: str) -> dict[str, object]:
    path = require_file(relative)
    return {
        "path": relative,
        "sha256": sha256_file(path),
        "size_bytes": path.stat().st_size,
    }


def entries_for_files(paths: list[str]) -> list[dict[str, object]]:
    return [file_entry(relative) for relative in sorted(paths)]


def entries_for_glob(directory: str, pattern: str, *, required: bool) -> list[dict[str, object]]:
    base = ROOT / directory
    if not base.is_dir():
        if required:
            raise SystemExit(f"missing manifest input directory: {directory}")
        return []
    paths = sorted(path for path in base.glob(pattern) if path.is_file())
    if required and not paths:
        raise SystemExit(f"manifest input directory has no {pattern} files: {directory}")
    return [file_entry(rel(path)) for path in paths]


def digest_entries(entries: list[dict[str, object]]) -> str:
    payload = json.dumps(entries, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def build_manifest() -> dict[str, object]:
    sections: dict[str, list[dict[str, object]]] = {}
    for section, paths in REQUIRED_FILES.items():
        sections[section] = entries_for_files(paths)
    for section, (directory, pattern) in RESEARCH_OBJECT_DIRS.items():
        sections[section] = entries_for_glob(directory, pattern, required=True)
    for section, paths in RESEARCH_OBJECT_FILES.items():
        sections[section] = entries_for_files(paths)
    research_sections = [
        "preregistration",
        "bor_records",
        "srf_records",
        "der_records",
        "msr_records",
        "comparative_dataset",
        "analysis",
        "retained_classification",
        "cohort_conclusion",
    ]
    schema_versions = sorted(entry["path"] for entry in sections["schemas"])

    return {
        "object_type": "PublicationStateManifest",
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "protocol_version": PROTOCOL_VERSION,
        "investigation_id": INVESTIGATION_ID,
        "manifest_path": rel(OUTPUT_PATH),
        "hash_algorithm": "sha256",
        "publication_state": {
            "protocol_version": PROTOCOL_VERSION,
            "dataset_path": RESEARCH_OBJECT_FILES["comparative_dataset"][0],
            "schema_paths": schema_versions,
            "research_object_manifest_hash": digest_entries(
                [entry for section in research_sections for entry in sections[section]]
            ),
            "dependency_contract_hash": digest_entries(sections["dependency_contracts"]),
            "build_environment_identifier": "repository-local; runtime supplied by CI or caller; see .github/workflows/validate.yml",
            "excluded_mutable_outputs": EXCLUDED_MUTABLE_OUTPUTS,
        },
        "sections": sections,
        "generation": {
            "builder": "scripts/build_publication_manifest.py",
            "mode": "deterministic-rebuild",
            "repository_root": ".",
        },
    }


def stable_bytes(data: dict[str, object]) -> bytes:
    return (json.dumps(data, indent=2, sort_keys=False) + "\n").encode("utf-8")


def check_committed(expected: dict[str, object]) -> None:
    if not OUTPUT_PATH.is_file():
        raise SystemExit(f"missing publication-state manifest: {rel(OUTPUT_PATH)}")
    committed_bytes = OUTPUT_PATH.read_bytes()
    committed = json.loads(committed_bytes)
    if not isinstance(committed, dict):
        raise SystemExit("committed publication-state manifest must be a JSON object")
    if committed != expected:
        raise SystemExit("committed publication-state manifest structure differs from deterministic rebuild")
    if committed_bytes != stable_bytes(expected):
        raise SystemExit("committed publication-state manifest bytes differ from deterministic rebuild")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="validate committed manifest freshness without writing")
    args = parser.parse_args()

    manifest = build_manifest()
    if args.check:
        check_committed(manifest)
        print(f"publication-state manifest fresh: {rel(OUTPUT_PATH)}")
        return
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_bytes(stable_bytes(manifest))
    print(f"wrote {rel(OUTPUT_PATH)}")


if __name__ == "__main__":
    main()
